# Generated by Django 4.1.7 on 2023-02-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_addition_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Sub_SubCategory name')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcateg', to='main.subcategory')),
            ],
            options={
                'verbose_name': 'Sub_SubCategory',
                'verbose_name_plural': 'Sub_SubCategories',
            },
        ),
    ]
