# Generated by Django 4.1.7 on 2023-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sub_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_subcategory',
            name='img',
            field=models.ImageField(default=1, upload_to='media', verbose_name='Sub_SubCategory image'),
            preserve_default=False,
        ),
    ]
