# Generated by Django 4.1.7 on 2023-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sub_subcategory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_subcategory',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Sub_SubCategory image'),
            preserve_default=False,
        ),
    ]
