# Generated by Django 4.1.7 on 2023-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sub_subcategory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_subcategory',
            name='price',
            field=models.IntegerField(verbose_name='Sub_SubCategory price'),
        ),
    ]
